### ISSUE TITLE
[Doc] v0.12 millstone document plan

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2214]
## Documentation Scope

Let's plan how many documents need to be created or updated in 0.12;

## Describe the Change
- [ ] Changes from 0.11 to 0.12. (Including break changing and influences after upgrade) @klesh 
- [x] [Require] Create a new config-ui user manual (related to 3&7). #2245  @e2corporation write and  @yumengwang03 review. 
- [x] #2286 @Startrekzky 
- [x] #2287 @Startrekzky 
- [x] #2285 @likyh 
- [x] #2301 @klesh 
- [x] #2409 @klesh 
- [x] 6. [Require] update demo in main readme. #2242 @yumengwang03 
- [ ] 7. [Optional] How to use connectionHelper to give a plugin the ability to deal with multi-connection.
- [ ] 8. [Optional] Why do we move transformation rules to `task.options`.
- [ ] 9. [Optional] How `Dal` help us write unit-test easily.
- [ ] 10. [Optional] Why we decide to write the e2e test and what we suggest to write the e2e test.
- [ ] 11. [Optional] What dashboard can we build with the existing plugins.

extract from https://github.com/apache/incubator-devlake/issues/1979

**Comment by Startrekzky** [comment]
Awesome. I'll take 'task 3'

**Comment by yumengwang03** [comment]
I'll work on no. 11 and review no.2

**Comment by yumengwang03** [comment]
Please note: the title of the docs can be defined by yourself. But please do not use questions for titles, such as "How to...". 

For example:
Do: Config UI User Manual
Don't: How to use Config UI

**Comment by Startrekzky** [comment]
All required sub-issues have been closed.
