### ISSUE TITLE
[Doc][Data Model] Domain layer schema should be updated to v0.12

### ISSUE THREAD

**Issue by Startrekzky** [apache/incubator-devlake#2612]
## Documentation Scope
[Apache DevLake's Domain Layer Schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema)

## Describe the Change
This doc should be updated to v0.12.0

- [x] DWM models should be removed
![image](https://user-images.githubusercontent.com/14050754/180999772-9e125cb1-9b00-4b3f-8b75-62952dbeefbe.png)
- [x] Team-related entities should be added #2361
- [x] PR comments/reviews entities should be updated #2452 
- [x] Commit files related entities should be added #953 
- [ ] go through and update all modified entities
