### ISSUE TITLE
[refactor][config-ui] ConfigUI refactor

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#2744]
# Config-ui Some Refactor Epic

- [ ] such as implementing the Data Models I described
- [x] adding Pagination feature to Blueprints Grid https://github.com/apache/incubator-devlake/pull/2780
- [x] restoring Cypress Tests to the stack
- [ ] support dynamic connection edit https://github.com/apache/incubator-devlake/issues/2826
- [x] extract some high cohesion hooks to reduce the number of useState.

====================== old content ===================

### What and why to refactor
Now, `config-ui` can run normally, but some slight confusion when developing. We shall fix them.

Detail as below:
##### 1. we defined too many vars in the global context (here mean pages), and they related with each other by `useEffect` in parent and son components.
Such as `activeTransformation` and `newTransformation` in **old code**:
`activeTransformation` is defined in `create-blueprint.jsx`, and it passed like this: `create-blueprint.jsx` -> `DataTransformations.jsx` -> `DataTransformations.jsx` -> `ProviderTransformationSettings.jsx` -> `jira.jsx`. `setActiveTransformation` is defined in `create-blueprint.jsx`, but it is called in several `useEffect`. 
Another similar var `newTransformation` is defined in `DataTransformations.jsx`.
That cause new developer to spend a lot of unnecessary time learning how the program works.

##### solution
We can do these actions to reduce the learning curve for the new developer:
1. only update the local state (defined in the current component by `useState`) in the function of `useEffect`, which depends on the props (state passed by the parent).
2. call the function `onXXX`/`handleXXX`/`setXXX` passed by the parent only when listening on the local state bound with UI. 
1 and 2 mean we cannot use `useEffect` to update the parent state by depending on another parent state like:
https://github.com/apache/incubator-devlake/blob/main/config-ui/src/pages/configure/settings/jira.jsx#L99-L105

3. use `useMemo` when a var is computed and has no side effects when updated.
This action has been used in `activeTransformation`, and we need to use it in all computed vars. It's an excellent way to help the developer know how a state affects another state. 
4. pack the logic of one data model in a hook and define some UI state in the appropriate component instead of global.
https://github.com/apache/incubator-devlake/pull/2552/files#diff-6e1e4ac7737de3bc6a223b9020b4b7012f28750afc3c12a98517e1628f214ec4R80
The logic written in the hook will be more readable than written in some different files or callbacks. And the data hook can avoid related updating/query logic in the different callback.
5. These ways can help us reduce the number of `useState` and `useEffect`. But special cases always exist. If we have to pass state and callback from pageComponent to detailComponent, let's use Typescript to clarify how to use them.
An example:
https://github.com/apache/incubator-devlake/blob/main/config-ui/src/pages/blueprints/create-blueprint.jsx#L591-L594
`addProjectTransformation` call `setConfiguredProject` in `create-blueprint.jsx`;
`addProjectTransformation` passed to `DataTransformations.jsx`;
and it passed to `StandardStackedList.jsx` as `onAdd` and `onChange`;

https://github.com/apache/incubator-devlake/blob/main/config-ui/src/pages/blueprints/create-blueprint.jsx#L596-L599
`addBoardTransformation` and `setConfiguredBoard` has the similar path.

But notice, they have similar names and similar using, but the param of `setConfiguredProject` is ID and the param of `setConfiguredBoard` is Object ...
Typescript can help us know how to use a state or callback when it has been passed many times in son components and avoid new committers, who don't notice the gap, using these setter functions wrong.

**Comment by likyh** [comment]
I'll start after discussions.

**Comment by likyh** [comment]
@e2corporation I agree with you on the use of typescript. We can use ts gradually and discreetly. Now we can name `configuredProject` as `configuredProjectId` to avoid this question.

>> 1. only update the local state (defined in the current component by useState) in the function of useEffect, which depends on the props (state passed by the parent).
> > 2. call the function onXXX/handleXXX/setXXX passed by the parent only when listening on the local state bound with UI.
1 and 2 mean we cannot use useEffect to update the parent state by depending on another parent state like:
https://github.com/apache/incubator-devlake/blob/main/config-ui/src/pages/configure/settings/jira.jsx#L99-L105
>
> Not sure if I understand what problem you are trying to identify here, initial state is passed down from parent. In the case of JIRA (like all other providers) all it's settings is routed through one settings handler (onSettingsChange) which stores transformation settings keyed by Board ID (JIRA) and Project Name (GitHub) and Project ID (GitLab)

I notice 2 refactors here:
1. Look at this code. This `useEffect` deps on `configuredBoard` passed from parent and call `onSettingsChange` passed from parent. It will cause `onSettingsChange` to call unexpectedly when its parent change `configuredBoard`. Son component should not add new connections between the parent's state and the parent's callback. Or it will cause the parent component to need to know all run detail in its children.
https://github.com/apache/incubator-devlake/blob/b31ec914f586ee043af6be18bb734dcbb29d6c59/config-ui/src/pages/configure/settings/jira.jsx#L99-L105
2. Maybe some states can be defined in son components. Such as `configuredProject`/`configuredBoard` can be defined in `DataTransformations` instead of `create-blueprint.jsx`, because it just an UI state in step 3. Of couse, it's just an example to describe what situation I mean, or maybe there are some unavoidable reasons to define these states in page components. Just an example to show how to reduce vars in the global context.

**Comment by e2corporation** [comment]
@likyh 

1. This is old code you are referencing, The `OnSettings` change here has been wrapped in an if check to ensure that configured board is defined so "undefined" board objects are not created. This interaction is just fine.

2. `configuredBoard` and `configuredProject` are defined in the DSM hook. It lives at parent level, does not need to be only defined in child component DataTransformations.

**Comment by likyh** [comment]
@e2corporation 
> 1. This is old code you are referencing, The `OnSettings` change here has been wrapped in an if check to ensure that configured board is defined so "undefined" board objects are not created. This interaction is just fine.
> 2. `configuredBoard` and `configuredProject` are defined in the DSM hook. It lives at parent level, does not need to be only defined in child component DataTransformations.

It's not enough to check if configuredBoard is undefined. Son component should not add new connections between the parent's state and the parent's callback. Maybe here we can call onSettingsChange only when typeMappingAll loaded and changed by user. Now configuredBoard changed in the parent component will lead to an unexcepted update in the parent component sight.

**Comment by e2corporation** [comment]
@likyh This is a reactive system, there is no unexpected update happening here. When `typeMappingAll` is changed and there's a board defined we write the configuration settings.

**Comment by likyh** [comment]
> @likyh This is a reactive system, there is no unexpected update happening here. When `typeMappingAll` is changed and there's a board defined we write the configuration settings. Why are you referencing connections? What connections are being added?

A better way is change `onSettingsChange` to `onConfiguredBoardChange` and use configuredBoard in parent component. That is one of the reasons for circular dependency.

**Comment by e2corporation** [comment]
@likyh This particular effect hasn't previously suffered nor does it currently suffer from a circular dependency. I do like the idea of having an `onConfiguredBoardChange`, though there would be one needed for projects as well if that were the case. As JIRA settings are working well at the moment there's no problem to solve with transformations. 

To clarify one way on how circular loops happen in an effect, an effect must not call the setter on the state variable for which the effect depends on. 

```
// Improper Use of Effect
useEffect(() => {
  setApple(apple)
}, [apple])
```

As far as your refactoring intentions go, first start small and work your way up from there.

1. Add Additional Memoizations
2. Update `StandardStackedList.jsx` if necessary. The whole reason there are 2 paths `addBoardTransformation` and `addProjectTransformation` is that these features could diverge based on product or business requirements. If we needed to perform any post-processing before setting the configured project or board, it would be done in the `addBoard...` and `addProject..` handlers. This is what the `setXXX` handlers are not passed directly.3. 

There's more meaningful work to do if you have time to invest on the frontend, such as implementing the Data Models I described, adding Pagination feature to Blueprints Grid, restoring Cypress Tests to the stack, and adding a Redux store (which I already had plans for and started locally), and more to mention.

**Comment by likyh** [comment]
@e2corporation Do you forget why the jira settings cannot merge to others? it's because of circular dependency...

**Comment by likyh** [comment]
> There's more meaningful work to do if you have time to invest on the frontend, such as implementing the Data Models I described, adding Pagination feature to Blueprints Grid, restoring Cypress Tests to the stack, and adding a Redux store (which I already had plans for and started locally), and more to mention.

All others I agree with except Redux. I'll work on one of it.

**Comment by likyh** [comment]
@e2corporation It seems not to be nonresponsive if githubProject's property changed. How to deal with it?
> const githubProject = new RepositoryProject({owner: 'e2corporation', repositoryName: 'incubator-devlake', type: 'string'})

**Comment by e2corporation** [comment]
@likyh No Data Models haven't been added to the codebase yet -- those were illustrative examples for local code of the models I am creating. Do not worry about configuredBoard and configuredProject for now until I get done with planning how I plan to utilize them.

You can look into the memoizations and tweaks to `StandardStackedList` or continue creating a new set of cypress tests for "blueprints" which will replace the old "pipelines" test group. I see that you have a PR open for tests already which is good.

**Comment by e2corporation** [comment]
This ticket is being closed, 3 core tasks have already been completed. Any outstanding requirements here will be replaced by #2882
