### ISSUE TITLE
[Refactor][Config-UI] Legacy Code Cleanup and Component Optimizations

### ISSUE THREAD

**Issue by e2corporation** [apache/incubator-devlake#2858]
**Config-UI Code Cleanup**

- [x] Cleanup Legacy V11 Components and other artifacts #3157
- [x] Remove Unused Routing definitions #3157
- [x] Resolve Lint Warnings #3157 
- [x] _Tryout_ New Data Models `TBD` #2928

**Milestone**
`v0.14.0`
