### ISSUE TITLE
[Feature][github_graphql] Merge github_graphql back to the plugin github

### ISSUE THREAD

**Issue by likyh** [apache/incubator-devlake#3529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### feature

- [ ] ~create PRs to submit the changes on Graphql to open source repo. https://github.com/shurcooL/graphql/compare/master...merico-dev:graphql:master~ The shurcooL does not deal PR since several month ago.
- [ ] sperate graphql collector to collector and extractor
- [x] ~merge back and replace duplicate collector and extractor~ Create a new option in Config-ui

### document

- [x] add a document to tell users Graphql only uses 1 token. (it enough, I collect 100 repo in one hour and rateLimit just cost 1500/5000)
- [x] add a document to tell users Graphql token need the privilege `read:user` `read:org`

### bug fix

- [x] add retyr logic for graphql request https://github.com/apache/incubator-devlake/issues/3521
- [x] GitHub Graphql will skip requesting all 100 users when one of them does not exist https://github.com/apache/incubator-devlake/issues/3491
- [x] The rate limit logic not end after collecting is finished https://github.com/apache/incubator-devlake/issues/3474
- [ ] https://github.com/apache/incubator-devlake/issues/3630
- [x] https://github.com/apache/incubator-devlake/issues/3635
- [x] https://github.com/apache/incubator-devlake/issues/3636

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
